### ISSUE TITLE
Error when try to access Logs index

### ISSUE THREAD

**Issue by rabol** [tomatophp/tomato-logs#1]
Accessing the logs in the admin panel gives you an error:

![Screenshot_2023-10-09_at_21 56 03](https://github.com/tomatophp/tomato-logs/assets/1177191/9dd9c50f-9380-4beb-8c8b-82c658bbeeed)

ans second time this error:

![Screenshot 2023-10-09 at 22 01 16](https://github.com/tomatophp/tomato-logs/assets/1177191/0322f2fa-6f75-4d64-875c-d58bd563cbe8)

To reproduce:

Follow the installation instructions, then install the plugins, the add the HasRole to the user model

**Comment by fadymondy** [comment]
Under the hood, this package creates and caches a SQLite database JUST for this model. It creates a table and populates the rows. If, for whatever reason, it can't cache a .sqlite file, it will default to using an in-memory sqlite database.

so you need to install php8.2-sqlite3 extension


if you are using Linux please use this command to install it

```bash
sudo apt-get install php8.2-sqlite3
```

**Comment by rabol** [comment]
I belive that I have that as my php version is 8.2 and I can easily run PEST and sqlite for my own projects

and... I'm on a MAC :)
